---
#
#  ________   ____ ______________ ____________________
#  \_____  \ |    |   \_   _____//   _____/\__    ___/
#  /  / \  \|    |   /|    __)_ \_____  \   |    |
#  /   \_/.  \    |  / |        \/        \  |    |
#  \_____\ \_/______/ /_______  /_______  /  |____|
#  \__>                \/        \/
#
# Русский перевод так же выполнен авторами:
# Автор: ABCDEF по другому CryptoWoman
# Ссылка на GitHub: https://github.com/cryptophpman/QuestSystem
# Лицензия: Apache License 2.0
# Приятного использования
#
#
###########################################################
## Информация:
## В этих элементах конфигурации можно использовать такие значения, как {TEST}
## Где они перечислены
###########################################################

buttons:
  create:
    quest-name: "Название квеста:"
    quest-name-placeholder: "убить 10 криперов"
    block-id: "Блок/Сущности айди:"
    block-id-placeholder: "dirt"
  # все кнопки
  create-new-quest: "Создать новый квест"
  start-execution: "Начать выполнение"
  exit: "Выйти назад"
  quest-settings: "Настройки квеста"

# Titles подразумевается как текст сверзу формы
titles:
  create-quest: "Создание квеста title"
  quest-detail: "Детали квеста"
  quest-settings: "Настройки квеста"
  quest-list: "Список квестов"
  quest-menu: "Меню квестов"

# Контект текст ниже title
contents:
  # {NAME} - название квеста, айди блока
  # {COUNT} - количество того что надо добыть
  quest-detail: "{NAME} в количестве {COUNT}"
  # Дальше значения {NAME} и {COUNT} не работают
  quest-settings: "Выберите чтобы продолжить дальше!"
  quest-list: "Список квестов content"
  quest-menu: "Выберите кнопку"

messages:
  empty-parameter: "Вы указали пустой параметр"
  quest-created: "Квест был создан"
  error-load-quest: "Ошибка загрузки квеста"
  took-quest: "Вы начали выполнение квеста"
  quest-remove: "Вы успешно удалили квест"

# Права на использования настройки квестов (создания, и тп)
quest-panel-permission: "quest-settings.command"
...